name: FastAPI Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 12 * * 1"   # weekly run

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest httpx  # ensure test deps present

      # ---------------- Local API tests ----------------
      - name: Run Local API tests
        run: PYTHONPATH=. pytest v2_api/test_api_endpoints.py -v --disable-warnings

      # ---------------- Live API tests ----------------
      - name: Run Live API tests (optional)
        if: github.event_name == 'schedule'
        run: RUN_LIVE=true PYTHONPATH=. pytest v2_api/test_api_endpoints.py -v --disable-warnings