name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: python -m pip install --upgrade pip
    - name: Install Python requirements
      run: python -m pip install -r 01_miscellaneous/requirements.txt

    - name: Run tests
      run: pytest -v

